name: nubank_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  provider: ^5.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family:  NuIcons
      fonts:
        - asset: assets/fonts/NuIcons.ttf